name: seicheese
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter

  google_fonts: ^2.3.3
  google_sign_in: ^6.2.2

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/icons/google-icon.png
   - assets/icons/logo.jpg
   - assets/stamp/stamp.png
   - assets/pin/pin_1.png
   - assets/pin/pin_2.png
   - assets/pin/pin_3.png
   - assets/pin/pin_4.png
   - assets/pin/pin_5.png
